packages:
  - packages/*
catalog:
  zod: ^4.5.4
overrides:
  zod: 'catalog:'
allowBuilds:
  '@mongodb-js/zstd': true
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  electron: true
  esbuild: true
  lefthook: true
  node-liblzma: true
